spring.application.name=PASiR_Andrii_Kurliak
spring.datasource.url=jdbc:mysql://localhost:3306/artur_orfin_spring
spring.datasource.username=user-ak
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
app.jwt.secret=1234567890123456789012345678901234567890123456789012345678901234
app.cors.allowed-origins=http://localhost:3000,http://localhost:5173,http://localhost:5174,http://localhost:8080